name: CI-CD

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Autenticando o usuário no Docker
        uses: docker/login-action@v2.0.0
        with:
          username: ${{secrets.REGISTRY_USER}}
          password: ${{secrets.REGISTRY_PWD}}
          
      - name: Construindo a imagem e fazendo o build          
        uses: docker/build-push-action@v3.0.0
        with:
          file: ./src/Dockerfile
          context: ./src/
          push: true
          tags: |
            atilarampazo/kube-news:latest
            atilarampazo/kube-news:${{github.run_number}}

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - uses: actions/checkout@v3
      
      - name: Definindo o kubeconfig
        uses: Azure/k8s-set-context@v2
        with:
           method: kubeconfig
           kubeconfig: ${{secrets.K8S_CONFIG}}
           
      - name: Efetuando Deploy no Kubernets
        uses: Azure/k8s-deploy@v3.1
        with:
          images: atilarampazo/kube-news:${{github.run_number}}
          manifests:  |
            k8s/deployment.yaml
      
      
      
